enum Status {
  NOT_CHECKED_IN = "NOT_CHECKED_IN",
  CHECKED_IN = "CHECKED_IN",
  INTERVIEWING = "INTERVIEWING",
  INTERVIEWED = "INTERVIEWED",
  BROWSING_PROFILE = "BROWSING_PROFILE",
}

export default Status;
